heat_template_version: 2015-04-30

description: extra config for post-deployment

# Note extra parameters can be defined, then passed data via the
# environment parameter_defaults, without modifying the parent template
parameters:
  servers:
    type: json
  input_values:
    type: json

resources:
  ExtraConfig:
    type: OS::Heat::SoftwareConfig
    properties:
      group: script
      config: |
        #!/bin/sh
        systemctl restart httpd

  ExtraDeployments:
    type: OS::Heat::SoftwareDeploymentGroup
    properties:
      servers:  {get_param: [servers, 'Controller'] }
      config: {get_resource: ExtraConfig}
      actions: ['CREATE','UPDATE']
      input_values: {get_param: input_values}
