#This file is an example of an environment file for defining the isolated
#networks and related parameters.
resource_registry:
  # Network Interface templates to use (these files must exist)
#  OS::TripleO::BlockStorage::Net::SoftwareConfig:
#    ../network/config/single-nic-vlans/cinder-storage.yaml
  OS::TripleO::Compute::Net::SoftwareConfig:
    /home/stack/osp10/templates/nic-config/compute.yaml
  OS::TripleO::Controller::Net::SoftwareConfig:
    /home/stack/osp10/templates/nic-config/controller.yaml
#  OS::TripleO::ObjectStorage::Net::SoftwareConfig:
#    ../network/config/single-nic-vlans/swift-storage.yaml
#  OS::TripleO::CephStorage::Net::SoftwareConfig:
#    ../network/config/single-nic-vlans/ceph-storage.yaml

parameter_defaults:
  # This section is where deployment-specific configuration is done
  # CIDR subnet mask length for provisioning network
  ControlPlaneSubnetCidr: '24'
  # Gateway router for the provisioning network (or Undercloud IP)
  ControlPlaneDefaultRoute: 192.168.24.2
  EC2MetadataIp: 192.168.24.2  # Generally the IP of the Undercloud
  # Customize the IP subnets to match the local environment
  InternalApiNetCidr: 192.168.54.0/24
  StorageNetCidr: 192.168.34.0/24
  StorageMgmtNetCidr: 192.168.44.0/24
  TenantNetCidr: 172.16.0.0/24
  ExternalNetCidr: 10.0.0.0/24
  # Customize the VLAN IDs to match the local environment
  InternalApiNetworkVlanID: 20
  StorageNetworkVlanID: 30
  StorageMgmtNetworkVlanID: 40
  TenantNetworkVlanID: 50
  ExternalNetworkVlanID: 10
  # Customize the IP ranges on each network to use for static IPs and VIPs
  InternalApiAllocationPools: [{'start': '192.168.54.10', 'end': '192.168.54.200'}]
  StorageAllocationPools: [{'start': '192.168.34.10', 'end': '192.168.34.200'}]
  StorageMgmtAllocationPools: [{'start': '192.168.44.10', 'end': '192.168.44.200'}]
  TenantAllocationPools: [{'start': '172.16.0.10', 'end': '172.16.0.200'}]
  # Leave room if the external network is also used for floating IPs
  ExternalAllocationPools: [{'start': '10.0.0.10', 'end': '10.0.0.50'}]
  # Gateway router for the external network
  ExternalInterfaceDefaultRoute: 10.0.0.1
  # Uncomment if using the Management Network (see network-management.yaml)
  # ManagementNetCidr: 10.0.1.0/24
  # ManagementAllocationPools: [{'start': '10.0.1.10', 'end': '10.0.1.50'}]
  # Use either this parameter or ControlPlaneDefaultRoute in the NIC templates
  # ManagementInterfaceDefaultRoute: 10.0.1.1
  # Define the DNS servers (maximum 2) for the overcloud nodes
  DnsServers: ["192.168.121.1","8.8.8.8"]
  # List of Neutron network types for tenant networks (will be used in order)
  NeutronNetworkType: 'vxlan,vlan'
  # The tunnel type for the tenant network (vxlan or gre). Set to '' to disable tunneling.
  NeutronTunnelTypes: 'vxlan'
  # Neutron VLAN ranges per network, for example 'datacentre:1:499,tenant:500:1000':
  # NeutronNetworkVLANRanges: 'datacentre:1:1000'
  # Customize bonding options, e.g. "mode=4 lacp_rate=1 updelay=1000 miimon=100"
  # for Linux bonds w/LACP, or "bond_mode=active-backup" for OVS active/backup.
  BondInterfaceOvsOptions: "bond_mode=active-backup"
  NeutronBridgeMappings: 'datacentre:br-ex,baremetal:br-baremetal'
  NeutronFlatNetworks: datacentre,baremetal
  # Fixed IPs for TLS/SSL
  PublicVirtualFixedIPs: [{'ip_address':'10.0.0.9'}]
