heat_template_version: newton

description: >
  Configure sshd_config

parameters:
  ServiceNetMap:
    default: {}
    description: Mapping of service_name -> network name. Typically set
                 via parameter_defaults in the resource registry.  This
                 mapping overrides those in ServiceNetMapDefaults.
    type: json
  EndpointMap:
    default: {}
    description: Mapping of service endpoint -> protocol. Typically set
                 via parameter_defaults in the resource registry.
    type: json

outputs:
  role_data:
    description: Role data for the ssh
    value:
      service_name: sshd
      config_settings:
        SshServerOptions:
          HostKey:
            - '/etc/ssh/ssh_host_rsa_key'
            - '/etc/ssh/ssh_host_ecdsa_key'
            - '/etc/ssh/ssh_host_ed25519_key'
          SyslogFacility: 'AUTHPRIV'
          AuthorizedKeysFile: '.ssh/authorized_keys'
          PasswordAuthentication: 'no'
          ChallengeResponseAuthentication: 'no'
          GSSAPIAuthentication: 'yes'
          GSSAPICleanupCredentials: 'no'
          UsePAM: 'yes'
          UseDNS: 'no'
          X11Forwarding: 'yes'
          UsePrivilegeSeparation: 'sandbox'
          AcceptEnv:
            - 'LANG LC_CTYPE LC_NUMERIC LC_TIME LC_COLLATE LC_MONETARY LC_MESSAGES'
            - 'LC_PAPER LC_NAME LC_ADDRESS LC_TELEPHONE LC_MEASUREMENT'
            - 'LC_IDENTIFICATION LC_ALL LANGUAGE'
            - 'XMODIFIERS'
          Subsystem: 'sftp  /usr/libexec/openssh/sftp-server'
      step_config: |
        include ::tripleo::profile::base::sshd
